;this file for FamiTone2 library generated by text2data tool

Bloxzar_music_data:
	.byte 4
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256

@instruments:
	.byte $30 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $02
	.word @env3,@env0,@env0
	.byte $00
	.byte $30 ;instrument $03
	.word @env4,@env9,@env0
	.byte $00
	.byte $70 ;instrument $04
	.word @env5,@env10,@env0
	.byte $00
	.byte $f0 ;instrument $05
	.word @env6,@env0,@env0
	.byte $00
	.byte $30 ;instrument $06
	.word @env7,@env11,@env0
	.byte $00
	.byte $30 ;instrument $07
	.word @env8,@env12,@env0
	.byte $00
	.byte $30 ;instrument $08
	.word @env8,@env0,@env0
	.byte $00

@samples:
	.byte $00+FT_DPCM_PTR,$00,$00	;1
	.byte $00+FT_DPCM_PTR,$00,$00	;2
	.byte $00+FT_DPCM_PTR,$00,$00	;3
	.byte $00+FT_DPCM_PTR,$00,$00	;4
	.byte $00+FT_DPCM_PTR,$00,$00	;5
	.byte $00+FT_DPCM_PTR,$00,$00	;6
	.byte $00+FT_DPCM_PTR,$00,$00	;7
	.byte $00+FT_DPCM_PTR,$00,$00	;8
	.byte $00+FT_DPCM_PTR,$00,$00	;9
	.byte $00+FT_DPCM_PTR,$00,$00	;10
	.byte $00+FT_DPCM_PTR,$00,$00	;11
	.byte $00+FT_DPCM_PTR,$00,$00	;12
	.byte $00+FT_DPCM_PTR,$00,$00	;13
	.byte $00+FT_DPCM_PTR,$00,$00	;14
	.byte $00+FT_DPCM_PTR,$00,$00	;15
	.byte $00+FT_DPCM_PTR,$00,$00	;16
	.byte $00+FT_DPCM_PTR,$00,$00	;17
	.byte $00+FT_DPCM_PTR,$00,$00	;18
	.byte $00+FT_DPCM_PTR,$00,$00	;19
	.byte $00+FT_DPCM_PTR,$00,$00	;20
	.byte $00+FT_DPCM_PTR,$00,$00	;21
	.byte $00+FT_DPCM_PTR,$00,$00	;22
	.byte $00+FT_DPCM_PTR,$00,$00	;23
	.byte $00+FT_DPCM_PTR,$00,$00	;24
	.byte $00+FT_DPCM_PTR,$10,$0f	;25
	.byte $05+FT_DPCM_PTR,$19,$0f	;26
	.byte $0c+FT_DPCM_PTR,$1e,$0f	;27
	.byte $0c+FT_DPCM_PTR,$1e,$0e	;28
	.byte $0c+FT_DPCM_PTR,$1e,$0d	;29
	.byte $0c+FT_DPCM_PTR,$1e,$0c	;30
	.byte $00+FT_DPCM_PTR,$00,$00	;31
	.byte $00+FT_DPCM_PTR,$00,$00	;32
	.byte $00+FT_DPCM_PTR,$00,$00	;33
	.byte $00+FT_DPCM_PTR,$00,$00	;34
	.byte $00+FT_DPCM_PTR,$00,$00	;35
	.byte $00+FT_DPCM_PTR,$00,$00	;36
	.byte $00+FT_DPCM_PTR,$00,$00	;37
	.byte $00+FT_DPCM_PTR,$00,$00	;38
	.byte $00+FT_DPCM_PTR,$00,$00	;39
	.byte $00+FT_DPCM_PTR,$00,$00	;40
	.byte $00+FT_DPCM_PTR,$00,$00	;41
	.byte $00+FT_DPCM_PTR,$00,$00	;42
	.byte $00+FT_DPCM_PTR,$00,$00	;43
	.byte $00+FT_DPCM_PTR,$00,$00	;44
	.byte $00+FT_DPCM_PTR,$00,$00	;45
	.byte $00+FT_DPCM_PTR,$00,$00	;46
	.byte $00+FT_DPCM_PTR,$00,$00	;47
	.byte $00+FT_DPCM_PTR,$00,$00	;48
	.byte $00+FT_DPCM_PTR,$00,$00	;49
	.byte $00+FT_DPCM_PTR,$00,$00	;50
	.byte $00+FT_DPCM_PTR,$00,$00	;51
	.byte $00+FT_DPCM_PTR,$00,$00	;52
	.byte $00+FT_DPCM_PTR,$00,$00	;53
	.byte $00+FT_DPCM_PTR,$00,$00	;54
	.byte $00+FT_DPCM_PTR,$00,$00	;55
	.byte $00+FT_DPCM_PTR,$00,$00	;56
	.byte $00+FT_DPCM_PTR,$00,$00	;57
	.byte $00+FT_DPCM_PTR,$00,$00	;58
	.byte $00+FT_DPCM_PTR,$00,$00	;59
	.byte $00+FT_DPCM_PTR,$00,$00	;60
	.byte $00+FT_DPCM_PTR,$00,$00	;61
	.byte $00+FT_DPCM_PTR,$00,$00	;62
	.byte $00+FT_DPCM_PTR,$00,$00	;63

@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c9,$c9,$c8,$02,$c7,$c5,$c5,$c4,$c0,$00,$08
@env2:
	.byte $ca,$c9,$c4,$c3,$c3,$c1,$c0,$00,$06
@env3:
	.byte $c8,$c8,$c7,$c7,$c6,$c6,$c5,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0
	.byte $00,$0f
@env4:
	.byte $c9,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$c0,$00,$08
@env5:
	.byte $ca,$ca,$c9,$c9,$c8,$02,$c7,$c7,$c6,$02,$c5,$c5,$c4,$02,$c3,$c3
	.byte $c2,$02,$c1,$c1,$c0,$00,$14
@env6:
	.byte $c6,$c7,$03,$c8,$19,$c7,$c7,$c8,$07,$c7,$02,$c6,$02,$c5,$c4,$00
	.byte $0e
@env7:
	.byte $cf,$cf,$ce,$06,$cd,$cc,$cb,$ca,$c9,$c6,$06,$c0,$00,$0b
@env8:
	.byte $cb,$07,$ca,$04,$c9,$04,$c8,$02,$c7,$c6,$c0,$00,$0a
@env9:
	.byte $c2,$c0,$00,$01
@env10:
	.byte $bb,$ba,$c0,$00,$02
@env11:
	.byte $c0,$d3,$c0,$00,$02
@env12:
	.byte $c7,$c0,$00,$01


@song0ch0:
	.byte $fb,$04
@ref0:
	.byte $8a,$22,$8d,$22,$8d,$22,$8d,$22,$8d
@ref1:
	.byte $22,$8d,$22,$8d,$1e,$8d,$14,$8d
@ref2:
	.byte $22,$8d,$22,$8d,$22,$8d,$22,$8d
	.byte $ff,$08
	.word @ref1
	.byte $ff,$08
	.word @ref2
	.byte $ff,$08
	.word @ref1
	.byte $ff,$08
	.word @ref2
	.byte $ff,$08
	.word @ref1
@song0ch0loop:
@ref8:
	.byte $8e,$22,$8d,$22,$8d,$22,$8d,$22,$8d
	.byte $ff,$08
	.word @ref1
@ref10:
	.byte $22,$8d,$22,$8d,$22,$99,$8e,$36,$81
@ref11:
	.byte $3b,$23,$23,$23,$23,$37,$3b,$23,$23,$23,$23,$41,$3f,$37,$3b,$3a
	.byte $81
	.byte $ff,$08
	.word @ref0
	.byte $ff,$08
	.word @ref1
@ref14:
	.byte $22,$bd
@ref15:
	.byte $26,$95,$8c,$4f,$52,$4e,$56,$52,$52,$56,$4e,$52,$52,$4e,$56,$52
	.byte $5c,$56,$58,$5c,$56,$58
@ref16:
	.byte $52,$95,$8e,$1f,$23,$28,$95,$27,$28,$81
@ref17:
	.byte $2d,$29,$27,$28,$85,$27,$1f,$21,$22,$9d
@ref18:
	.byte $23,$19,$19,$22,$85,$23,$19,$19,$22,$85,$23,$19,$19,$22,$85,$22
	.byte $81
@ref19:
	.byte $29,$27,$23,$27,$29,$2d,$29,$26,$85,$1e,$91,$19,$1e,$81
@ref20:
	.byte $22,$89,$23,$22,$85,$23,$22,$85,$23,$23,$23,$29,$27,$23,$1e,$81
@ref21:
	.byte $1a,$85,$1b,$1b,$1b,$1b,$1b,$18,$85,$19,$19,$19,$19,$19,$18,$85
@ref22:
	.byte $15,$15,$15,$15,$15,$15,$15,$10,$85,$11,$11,$11,$11,$11,$11,$10
	.byte $81
@ref23:
	.byte $0f,$0f,$0f,$0f,$0f,$0f,$0f,$18,$85,$19,$15,$15,$11,$11,$0f,$0e
	.byte $81
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@ref24:
	.byte $8a,$30,$8d,$30,$8d,$30,$8d,$30,$8d
@ref25:
	.byte $30,$8d,$30,$8d,$30,$8d,$2c,$8d
@ref26:
	.byte $30,$8d,$30,$8d,$30,$8d,$30,$8d
	.byte $ff,$08
	.word @ref25
	.byte $ff,$08
	.word @ref26
	.byte $ff,$08
	.word @ref25
	.byte $ff,$08
	.word @ref26
	.byte $ff,$08
	.word @ref25
@song0ch1loop:
@ref32:
	.byte $90,$53,$59,$61,$5d,$58,$85,$4f,$52,$85,$4f,$53,$4f,$59,$5d,$53
	.byte $4e,$81
@ref33:
	.byte $52,$85,$4f,$52,$85,$4f,$53,$4f,$53,$4f,$49,$4f,$49,$45,$41,$44
	.byte $81
@ref34:
	.byte $48,$85,$45,$49,$4f,$49,$45,$48,$85,$49,$45,$41,$45,$41,$3b,$36
	.byte $81
@ref35:
	.byte $8e,$3b,$23,$23,$23,$23,$37,$3b,$23,$23,$23,$23,$41,$3f,$37,$3a
	.byte $85
@ref36:
	.byte $90,$48,$85,$45,$41,$48,$85,$45,$41,$49,$49,$45,$41,$49,$4f,$53
	.byte $58,$81
@ref37:
	.byte $48,$85,$45,$41,$45,$41,$3b,$41,$3a,$8d,$3e,$8d
@ref38:
	.byte $40,$95,$3b,$3f,$41,$3f,$3b,$40,$85,$3b,$3f,$40,$81
@ref39:
	.byte $44,$95,$3f,$41,$45,$41,$3f,$41,$44,$8d
@ref40:
	.byte $48,$8d,$48,$8d,$48,$8d,$48,$8d
@ref41:
	.byte $8e,$15,$15,$15,$15,$15,$15,$15,$19,$19,$19,$19,$0f,$0f,$0f,$0e
	.byte $85
@ref42:
	.byte $11,$11,$11,$11,$11,$11,$11,$11,$11,$11,$11,$11,$11,$11,$11,$10
	.byte $81
@ref43:
	.byte $15,$15,$15,$15,$15,$15,$15,$15,$19,$19,$19,$19,$1f,$1f,$1f,$1e
	.byte $81
@ref44:
	.byte $23,$23,$23,$23,$23,$23,$23,$23,$23,$19,$1f,$23,$29,$1f,$19,$1e
	.byte $81
@ref45:
	.byte $23,$23,$23,$23,$23,$23,$23,$23,$23,$23,$23,$23,$23,$23,$23,$22
	.byte $81
@ref46:
	.byte $23,$23,$23,$23,$23,$23,$23,$1f,$1f,$1f,$1f,$1f,$1f,$1f,$1f,$1e
	.byte $81
@ref47:
	.byte $1f,$1f,$1f,$1f,$1f,$1f,$1f,$29,$29,$29,$27,$27,$23,$23,$1f,$1e
	.byte $81
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@ref48:
	.byte $80,$53,$3b,$6b,$3b,$4f,$4f,$4d,$4e,$85,$49,$4f,$49,$4f,$53,$4f
	.byte $4c,$81
@ref49:
	.byte $53,$3b,$6b,$3b,$4f,$4f,$4d,$4e,$85,$49,$4f,$49,$4f,$53,$59,$52
	.byte $81
@ref50:
	.byte $53,$3b,$6b,$3b,$4f,$4f,$4d,$4e,$85,$49,$4f,$49,$4f,$53,$4f,$4c
	.byte $81
	.byte $ff,$11
	.word @ref49
	.byte $ff,$11
	.word @ref50
	.byte $ff,$11
	.word @ref49
	.byte $ff,$11
	.word @ref50
	.byte $ff,$11
	.word @ref49
@song0ch2loop:
@ref56:
	.byte $8e,$53,$3b,$6b,$3b,$4f,$4f,$4d,$4e,$85,$49,$4f,$49,$4f,$53,$4f
	.byte $4c,$81
	.byte $ff,$11
	.word @ref49
@ref58:
	.byte $40,$85,$3f,$41,$45,$41,$3f,$40,$85,$41,$3f,$3b,$3f,$3b,$31,$2c
	.byte $81
@ref59:
	.byte $45,$49,$31,$31,$31,$31,$45,$49,$31,$31,$31,$31,$4f,$4d,$45,$48
	.byte $81
@ref60:
	.byte $53,$3b,$6b,$3b,$41,$41,$3f,$40,$85,$3f,$41,$3f,$41,$45,$41,$3e
	.byte $81
@ref61:
	.byte $4f,$37,$67,$37,$41,$41,$3f,$41,$40,$8d,$44,$8d
@ref62:
	.byte $48,$bd
@ref63:
	.byte $4e,$bd
@ref64:
	.byte $97,$8e,$4f,$53,$58,$95,$57,$58,$81
@ref65:
	.byte $5d,$59,$57,$58,$85,$57,$4f,$51,$52,$9d
@ref66:
	.byte $53,$49,$49,$52,$85,$53,$49,$49,$52,$85,$53,$49,$49,$52,$85,$52
	.byte $81
@ref67:
	.byte $59,$57,$53,$57,$59,$5d,$59,$56,$85,$4e,$91,$49,$4e,$81
@ref68:
	.byte $52,$89,$53,$52,$85,$53,$52,$85,$53,$53,$53,$59,$57,$53,$4e,$81
@ref69:
	.byte $4a,$85,$4b,$4b,$4b,$4b,$4b,$48,$85,$49,$49,$49,$49,$49,$49,$48
	.byte $81
@ref70:
	.byte $45,$45,$45,$45,$45,$45,$45,$40,$85,$41,$41,$41,$41,$41,$41,$40
	.byte $81
@ref71:
	.byte $3f,$3f,$3f,$3f,$3f,$3f,$3f,$48,$85,$49,$45,$45,$41,$41,$3f,$3e
	.byte $81
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@ref72:
	.byte $bf
@ref73:
	.byte $bf
@ref74:
	.byte $bf
@ref75:
	.byte $bf
@ref76:
	.byte $82,$03,$17,$84,$17,$82,$17,$86,$09,$82,$17,$84,$17,$82,$17,$03
	.byte $17,$03,$17,$86,$09,$82,$17,$84,$17,$82,$16,$81
@ref77:
	.byte $03,$17,$84,$17,$82,$17,$86,$09,$82,$17,$84,$17,$82,$17,$03,$17
	.byte $03,$17,$86,$09,$82,$17,$84,$17,$82,$16,$81
	.byte $ff,$11
	.word @ref77
	.byte $ff,$11
	.word @ref77
@song0ch3loop:
@ref80:
	.byte $88,$16,$8d,$86,$09,$82,$17,$84,$17,$82,$17,$03,$17,$03,$17,$86
	.byte $09,$82,$17,$84,$17,$82,$16,$81
	.byte $ff,$11
	.word @ref77
	.byte $ff,$11
	.word @ref77
@ref83:
	.byte $03,$17,$84,$17,$82,$17,$86,$09,$82,$17,$84,$17,$82,$17,$03,$17
	.byte $03,$17,$86,$09,$82,$17,$84,$17,$86,$08,$81
	.byte $ff,$11
	.word @ref76
	.byte $ff,$11
	.word @ref77
	.byte $ff,$11
	.word @ref77
	.byte $ff,$11
	.word @ref77
	.byte $ff,$0f
	.word @ref80
	.byte $ff,$11
	.word @ref77
	.byte $ff,$11
	.word @ref77
	.byte $ff,$11
	.word @ref83
	.byte $ff,$11
	.word @ref76
	.byte $ff,$11
	.word @ref77
	.byte $ff,$11
	.word @ref77
	.byte $ff,$11
	.word @ref83
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@ref96:
	.byte $32,$bd
@ref97:
	.byte $a7,$32,$89,$32,$89
@ref98:
	.byte $32,$bd
@ref99:
	.byte $a7,$32,$85,$37,$37,$3a,$85
@ref100:
	.byte $32,$8d,$34,$8d,$32,$85,$32,$85,$34,$8d
	.byte $ff,$0a
	.word @ref100
	.byte $ff,$0a
	.word @ref100
@ref103:
	.byte $32,$8d,$34,$8d,$37,$37,$37,$37,$39,$39,$3b,$3c,$81
@song0ch4loop:
	.byte $ff,$0a
	.word @ref100
	.byte $ff,$0a
	.word @ref100
	.byte $ff,$0a
	.word @ref100
@ref107:
	.byte $32,$8d,$34,$8d,$32,$85,$32,$85,$34,$89,$34,$81
	.byte $ff,$0a
	.word @ref100
	.byte $ff,$0a
	.word @ref100
	.byte $ff,$0a
	.word @ref100
	.byte $ff,$0c
	.word @ref107
	.byte $ff,$0a
	.word @ref100
	.byte $ff,$0a
	.word @ref100
	.byte $ff,$0a
	.word @ref100
	.byte $ff,$0c
	.word @ref107
	.byte $ff,$0a
	.word @ref100
	.byte $ff,$0a
	.word @ref100
	.byte $ff,$0a
	.word @ref100
	.byte $ff,$0c
	.word @ref107
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$06
@song1ch0loop:
@ref120:
	.byte $8a,$22,$bd
@ref121:
	.byte $bf
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
	.byte $ff,$08
	.word @ref24
	.byte $ff,$08
	.word @ref25
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
	.byte $ff,$11
	.word @ref48
	.byte $ff,$11
	.word @ref49
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref126:
	.byte $bf
@ref127:
	.byte $bf
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref128:
	.byte $32,$bd
	.byte $ff,$05
	.word @ref97
	.byte $fd
	.word @song1ch4loop


@song2ch0:
	.byte $fb,$06
@song2ch0loop:
@ref130:
	.byte $8a,$22,$bd
@ref131:
	.byte $bf
	.byte $fd
	.word @song2ch0loop

@song2ch1:
@song2ch1loop:
	.byte $ff,$08
	.word @ref24
	.byte $ff,$08
	.word @ref25
	.byte $fd
	.word @song2ch1loop

@song2ch2:
@song2ch2loop:
	.byte $ff,$11
	.word @ref48
	.byte $ff,$11
	.word @ref49
	.byte $fd
	.word @song2ch2loop

@song2ch3:
@song2ch3loop:
@ref136:
	.byte $bf
@ref137:
	.byte $bf
	.byte $fd
	.word @song2ch3loop

@song2ch4:
@song2ch4loop:
@ref138:
	.byte $32,$bd
	.byte $ff,$05
	.word @ref97
	.byte $fd
	.word @song2ch4loop


@song3ch0:
	.byte $fb,$06
@song3ch0loop:
@ref140:
	.byte $8a,$22,$bd
@ref141:
	.byte $bf
	.byte $fd
	.word @song3ch0loop

@song3ch1:
@song3ch1loop:
	.byte $ff,$08
	.word @ref24
	.byte $ff,$08
	.word @ref25
	.byte $fd
	.word @song3ch1loop

@song3ch2:
@song3ch2loop:
	.byte $ff,$11
	.word @ref48
	.byte $ff,$11
	.word @ref49
	.byte $fd
	.word @song3ch2loop

@song3ch3:
@song3ch3loop:
@ref146:
	.byte $bf
@ref147:
	.byte $bf
	.byte $fd
	.word @song3ch3loop

@song3ch4:
@song3ch4loop:
@ref148:
	.byte $32,$bd
	.byte $ff,$05
	.word @ref97
	.byte $fd
	.word @song3ch4loop
